Class:
  mineur:
    items: "257:0"
    life: 16
  guerrier:
    items: "267:0"
    life: 30
  lutin:
    items: "347:0"
    life: 20
Minerais:
  fer: 10
  or: 50
  diamand: 150
  emeraude: 300

World: "world"

Equipe:
  a:
    x: 250
    y: 250
    z: 250
  b:
    x: 250
    y: 250
    z: 250
  c:
    x: 250
    y: 250
    z: 250
  d:
    x: 250
    y: 250
    z: 250
